/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application;

import Client.Client;
import java.awt.Color;

/**
 *
 * @author maybeitsmica
 */
public class MainSimple extends javax.swing.JFrame {

    private Client client;
    /**
     * Creates new form ChatSimple
     */
    public MainSimple(Client client) {
        
        this.client = client;
        
        initComponents();
        
        addMessageCurrent();
        addMessageCurrent();
        addMessageFriend();
        
        /*Box panelContainer = Box.createVerticalBox(); 
        panelContainer.setPreferredSize(new Dimension(0, 282));
        
        chatPanel.add(panelContainer, BorderLayout.PAGE_START);
        JScrollPane myScrollPaneContent = new JScrollPane(chatPanel);
        add(myScrollPaneContent);
        
        JLabel label = new JLabel("hello", SwingConstants.CENTER);
        label.setPreferredSize(new Dimension(100,50));
        
        panelContainer.add(label);
        panelContainer.revalidate();
        panelContainer.repaint();
        
        //getContentPane().add(panelContainer);
        
        
        myScrollPaneContent.revalidate();
        myScrollPaneContent.repaint();*/
    }
    
    private void addMessageCurrent(){
        addMessage(new Color(148, 205, 142), "maybeitsmica");
    }
    
    private void addMessageFriend(){
        addMessage(new Color(122, 169, 117), "micaela");
    }
    
    private void addMessage(Color color, String username){
        
        /*JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.setPreferredSize(new Dimension(60,40));
        panel.setMinimumSize(new Dimension(60,40));
        panel.setMaximumSize(new Dimension(300,40));
        panel.setBorder(new EmptyBorder(10, 15, 0, 0));
        
        JLabel label = new JLabel(username + "hello", SwingConstants.LEFT);
        //label.setMinimumSize(new Dimension(40,30));
        //label.setPreferredSize(new Dimension(100,30));
        label.setFont(new Font("arial", Font.PLAIN, 16));
        label.setBackground(color);
        label.setOpaque(true);
        label.setBorder(new EmptyBorder(3, 3, 3, 3));
        label.setAlignmentX(Component.LEFT_ALIGNMENT);
        
        panel.add(label);
        panel.setAlignmentX(Component.LEFT_ALIGNMENT);*/
        /*MessageInterface m = new MessageInterface(color, username);
        chatPanel.add(m.getMessage());
        chatPanel.revalidate();
        chatPanel.repaint();*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        friendUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        changeFriend = new javax.swing.JButton();
        chatPanel = new javax.swing.JPanel();
        sendFile = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(209, 210, 212));

        jPanel3.setBackground(new java.awt.Color(207, 124, 160));
        jPanel3.setPreferredSize(new java.awt.Dimension(595, 69));

        friendUsername.setBackground(new java.awt.Color(148, 205, 142));
        friendUsername.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Chat with");

        changeFriend.setBackground(new java.awt.Color(122, 169, 117));
        changeFriend.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        changeFriend.setForeground(new java.awt.Color(0, 0, 0));
        changeFriend.setText("Change");
        changeFriend.setBorder(null);
        changeFriend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeFriend(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(friendUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(friendUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        chatPanel.setMinimumSize(new java.awt.Dimension(0, 339));
        chatPanel.setPreferredSize(new java.awt.Dimension(0, 339));
        chatPanel.setLayout(new javax.swing.BoxLayout(chatPanel, javax.swing.BoxLayout.Y_AXIS));

        sendFile.setBackground(new java.awt.Color(207, 124, 160));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\kaela\\Documents\\NetBeansProjects\\fileChat\\src\\main\\java\\Images\\icons8-file-arrow-32.png")); // NOI18N
        jLabel2.setText("Send file");

        javax.swing.GroupLayout sendFileLayout = new javax.swing.GroupLayout(sendFile);
        sendFile.setLayout(sendFileLayout);
        sendFileLayout.setHorizontalGroup(
            sendFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sendFileLayout.setVerticalGroup(
            sendFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(chatPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sendFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(chatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sendFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeFriend(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeFriend

        String username = friendUsername.getText();

        // comprobar si está conectado / existe?

    }//GEN-LAST:event_changeFriend

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeFriend;
    private javax.swing.JPanel chatPanel;
    private javax.swing.JTextField friendUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel sendFile;
    // End of variables declaration//GEN-END:variables
}
